name: Ejecutar Colab

on:
  schedule:
    - cron: "0 2 * * *"  # Se ejecuta a las 2:00 AM UTC todos los días
  workflow_dispatch: # Permite la ejecución manual desde la interfaz de GitHub Actions


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Autenticar con Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Ejecutar el cuaderno de Colab
        run: |
          pip install google-colab  # Asegúrate de tener google-colab instalado
          # Reemplaza con la ruta a tu cuaderno en el repositorio
          NOTEBOOK_PATH="nombre_de_tu_cuaderno.ipynb"
          #El nombre del archivo de salida .ipynb
          OUTPUT_NOTEBOOK="output.ipynb"
          python -c "from google.colab import drive; drive.mount('/content/drive'); import subprocess; subprocess.run(['colab', 'run', '$NOTEBOOK_PATH', '--output', '$OUTPUT_NOTEBOOK']);"
