name: Ejecutar Cuaderno

on:
  schedule:
    - cron: "0 2 * * *"  # Se ejecuta a las 2:00 AM UTC todos los días
  workflow_dispatch:  # Permite la ejecución manual desde la interfaz de GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # o la versión que estés usando

      - name: Crear entorno virtual e instalar dependencias
        run: |
          python -m venv venv  # Usar el módulo venv
          source venv/bin/activate  # Activar el entorno virtual
          pip install papermill ipykernel  # Instalar papermill y ipykernel
          python -m ipykernel install --user --name=python3 --display-name "Python 3"  # Registrar el kernel

      - name: Ejecutar el cuaderno
        run: |
          source venv/bin/activate  # Asegurarse de activar el entorno virtual
          NOTEBOOK_PATH="Untitled14.ipynb"  # Reemplaza con tu nombre de cuaderno
          OUTPUT_NOTEBOOK="output_cuaderno.ipynb"  # El archivo de salida
          papermill $NOTEBOOK_PATH $OUTPUT_NOTEBOOK  # Ejecutar el cuaderno con papermill
